# This file is an example on how to use CI on Gitlab DSO platform, it is not yet functionnal with environnment
# references for includes are at https://github.com/cloud-pi-native/gitlab-ci-catalog
stages:
  - read-secret
  - build-push

include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

vault:read_secret:
  stage: read-secret
  extends: .vault:read_secret

build-push-branches:
  extends: .kaniko:build-push
  stage: build-push
  variables:
    WORKING_DIR: .
    IMAGE_NAMES: explorer:$CI_BRANCH