apiVersion: v1
kind: Service
metadata:
  name: cnsc-s3-app-s3-upload-app-secondary
spec:
  selector:
    app: cnsc-s3-app-s3-upload-app-secondary
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
