apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnsc-s3-app-s3-upload-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnsc-s3-app-s3-upload-app
  template:
    metadata:
      labels:
        app: cnsc-s3-app-s3-upload-app
    spec:
      containers:
      - name: cnsc-s3-app-s3-upload-app
        image: docker.io/etiquet/s3-upload-app:1.41
        ports:
        - containerPort: 5000
        env:
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_BUCKET
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_SECRET_ACCESS_KEY
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_REGION
        - name: S3_URL
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_URL
        - name: S3_FOLDER
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_FOLDER
        - name: S3_SKIP_VERIFY
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_SKIP_VERIFY    
        - name: S3_WEBHOOK
          valueFrom:
            secretKeyRef:
              name: s3-upload-app-secret
              key: S3_WEBHOOK  
        volumeMounts:
        - name: tmp-folder
          mountPath: /tmp
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem : true
          runAsUser: 1000
          runAsGroup: 1000
      imagePullSecrets:
      - name: regcred
      volumes:
      - name: tmp-folder
        emptyDir:
          sizeLimit: 500Mi
