apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.global.namespace }} 
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: {{ .Values.app.name }}
        image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
        ports:
        - containerPort: 5000
        env:
        - name: S3_FOLDER
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-config
              key: S3_FOLDER
        - name: S3_SKIP_VERIFY
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-config
              key: S3_SKIP_VERIFY
        - name: S3_WEBHOOK
          valueFrom:
            configMapKeyRef:
              name: {{ .Values.app.name }}-config
              key: S3_WEBHOOK
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-secrets
              key: S3_BUCKET
        - name: S3_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-secrets
              key: S3_ACCESS_KEY_ID
        - name: S3_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-secrets
              key: S3_SECRET_ACCESS_KEY
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-secrets
              key: S3_REGION
        - name: S3_URL
          valueFrom:
            secretKeyRef:
              name: {{ .Values.app.name }}-secrets
              key: S3_URL              
{{if .Values.app.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.app.imagePullSecrets }}
        namespace: odfclient
{{- end }} 