{{ if .Values.global.createsecretmaps }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secrets
  namespace: {{ .Values.global.namespace }} 
type: Opaque
data:
  S3_BUCKET: {{ .Values.app.s3Bucket | b64enc | quote }}
  S3_ACCESS_KEY_ID: {{ .Values.app.s3AccessKeyId | b64enc | quote }}
  S3_SECRET_ACCESS_KEY: {{ .Values.app.s3SecretAccessKey | b64enc | quote }}
  S3_REGION: {{ .Values.app.s3Region | b64enc | quote }}
  S3_URL: {{ .Values.app.s3Url | b64enc | quote }}
{{ end }}