apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: s3-upload-content-project
  namespace: odfclient
spec:
  description: Project for managing the S3 Upload Content Application
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist:
    - group: '*'
      kind: 'ResourceQuota'
  roles:
    - name: admin
      description: Admin role with full access
      policies:
        - p, proj:s3-upload-content-project:admin, applications, *, *, allow
      groups:
        - admin
